from sqlalchemy import Integer, String
from sqlalchemy.orm import Mapped, mapped_column
from ugs.models.db import db

class Screenshot(db.Model):
    steam_id = db.Column(db.String, primary_key=True)
    ugs_user = db.Column(db.String)
    creator = db.Column(db.String)
    creator_appid = db.Column(db.String)
    consumer_appid = db.Column(db.String)
    consumer_shortcutid = db.Column(db.String)
    filename = db.Column(db.String)
    file_size = db.Column(db.String)
    preview_file_size = db.Column(db.String)
    file_url = db.Column(db.String)
    preview_url = db.Column(db.String)
    url = db.Column(db.String)
    hcontent_file = db.Column(db.String)
    hcontent_preview = db.Column(db.String)
    title = db.Column(db.String)
    short_description = db.Column(db.String)
    time_created = db.Column(db.String)
    time_updated = db.Column(db.String)
    visibility = db.Column(db.String)
    flags = db.Column(db.String)
    workshop_file = db.Column(db.String)
    workshop_accepted = db.Column(db.String)
    show_subscribe_all = db.Column(db.String)
    num_comments_developer = db.Column(db.String)
    num_comments_public = db.Column(db.String)
    banned = db.Column(db.String)
    ban_reason = db.Column(db.String)
    banner = db.Column(db.String)
    can_be_deleted = db.Column(db.String)
    app_name = db.Column(db.String)
    file_type = db.Column(db.String)
    can_subscribe = db.Column(db.String)
    subscriptions = db.Column(db.String)
    favorited = db.Column(db.String)
    followers = db.Column(db.String)
    lifetime_subscriptions = db.Column(db.String)
    lifetime_favorited = db.Column(db.String)
    lifetime_followers = db.Column(db.String)
    lifetime_playtime = db.Column(db.String)
    lifetime_playtime_sessions = db.Column(db.String)
    views = db.Column(db.String)
    image_width = db.Column(db.String)
    image_height = db.Column(db.String)
    image_url = db.Column(db.String)
    num_children = db.Column(db.String)
    num_reports = db.Column(db.String)
    score = db.Column(db.String)
    votes_up = db.Column(db.String)
    votes_down = db.Column(db.String)
    language = db.Column(db.String)
    maybe_inappropriate_sex = db.Column(db.String)
    maybe_inappropriate_violence = db.Column(db.String)
    revision_change_number = db.Column(db.String)
    revision = db.Column(db.String)
    ban_text_check_result = db.Column(db.String)
    raw_activity = db.Column(db.String)